# Use the official Python image as base
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Python script into the container
COPY task-1.py /app

# Install any dependencies if needed (none in this case)

# Command to run the Python script
CMD ["python", "task-1.py"]

